### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ammarahm-ed** [ammarahm-ed/react-native-scoped-storage#14]
Implement the following methods
- [x]  `copyFile(to:string,from:string)`: copy a file from one directory to another
- [ ]  `moveFile(to:string,from:string)`: move a file from on location to another
- [x] `stat(uri:string)`: list info about a file/directory for a given uri

**Comment by abhishek-pokhriyal** [comment]
Hey @ammarahm-ed, were you able to make any progress on any of the 2 remaining methods?

**Comment by eramudeep** [comment]
anytime line on **moveFile** ..?
